# Generated by Django 4.2.7 on 2023-12-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_img',
            field=models.ImageField(default=1, upload_to='post/'),
            preserve_default=False,
        ),
    ]
